javapathfinder/jpf-core

- README.md
The badge to show the build status of the master branch of the jpf-core repository.
> Embed Travis status image to README.md

- build.xml
This fixes the error:
[javac] javac: invalid flag: -Xlint:-sunapi
Fixes: #25
> Remove -Xlint:sunapi from build.xml

- build.xml
This is a fixup to the commit: 880b4ca
> Update ant target -compile-classes

- build.gradle
> Implemented log summary and updated log configurations

- build.xml
Reverts javapathfinder/jpf-core#48
> Revert "Format output of ant 'test' target"

- build.gradle
> Adds support to Jar tasks on Gradle build

- src/tests/gov/nasa/jpf/test/java/util/CalendarTest.java
Demonstration of a bug described in #180 . To observe it, run this class on JPF.
> Calendar peer bug demonstration

- src/main/gov/nasa/jpf/search/Search.java
Fixed spelling and grammar errors, added verbosity to existing javadoc
and added javadoc where none previously existed.
> Updated Search.java documentation

- src/main/gov/nasa/jpf/vm/ClassLoaderInfo.java
Fix setting wrong typename in ClassLoaderInfo.getResolvedFuncObjType
> Fix Lambda expressions issue

- .gitignore
- src/main/gov/nasa/jpf/jvm/bytecode/INVOKEDYNAMIC.java
- src/main/gov/nasa/jpf/vm/FunctionObjectFactory.java
- src/tests/java11/StringConcatenationTest.java
Fixed string concatenation error described in issue #236.
> Pull request for issue #236

- src/classes/modules/java.base/java/lang/Class.java
- src/classes/modules/java.base/java/lang/Module.java
- src/main/gov/nasa/jpf/jvm/JVMClassInfo.java
- src/main/gov/nasa/jpf/jvm/ResolvedClasses.java
- src/main/gov/nasa/jpf/vm/ClassInfo.java
- src/main/gov/nasa/jpf/vm/ClassLoaderInfo.java
- src/peers/gov/nasa/jpf/vm/JPF_java_lang_Class.java
Add module path to resolved resource name
> Fix Class getResource method

- README.md
Improvised documentation for better understanding
:)
> Indentation and grammatical corrrections

- .github/workflows/simple_build.yml
This runs the tests but does not check the detailed test output.
> Add gradle task to run PolDet tests (partially addresses issue #288)

- src/main/gov/nasa/jpf/vm/Verify.java
> remove the empty bodies of some methods in Verify.java, and add native qualifiers for them

- src/tests/PolDet/PolDetExamples.java
- src/tests/PolDet/PolDetMain.java
- src/tests/ThreadLocalTest/App.java
adding missing import statements
> Adding Import Statments

- src/main/gov/nasa/jpf/jvm/bytecode/JVMArrayElementInstruction.java
- src/tests/gov/nasa/jpf/test/mc/threads/RaceTest.java
This is a backport of PR #345 on `main` branch. All tests passed.
> Fix PreciseRaceDetector false alarms (#344), a backport of PR #345

- src/peers/gov/nasa/jpf/vm/JPF_java_lang_Class.java
- src/tests/gov/nasa/jpf/test/java/lang/ClassTest.java
Same as Pull Request #372, but against the `java-10-gradle` branch.
> Fixed Class.forName for primitive array types

- src/main/gov/nasa/jpf/jvm/JVMClassInfo.java
- src/main/gov/nasa/jpf/vm/BootstrapMethodInfo.java
- src/main/gov/nasa/jpf/vm/ClassInfo.java
- src/tests/gov/nasa/jpf/test/java/io/ObjectStreamTest.java
- src/tests/java8/LambdaTest.java
This patch adds support for serializable lambda expression and also fixes #234.
> Add serializable lambda expression support (#234)

- src/classes/modules/java.base/java/lang/System.java
- src/tests/gov/nasa/jpf/test/java/lang/SystemTest.java
The original patch can be found [here](https://github.com/javapathfinder/jpf-core/commit/55f4f09d392d1f721119ec3382caeffcefc9a895).
Adds one test : `testSystemIn`
All 934 tests pass.
Thanks!
> Apply patch to add System.in.available()

- src/classes/modules/java.base/jdk/internal/misc/Unsafe.java
- src/peers/gov/nasa/jpf/vm/JPF_jdk_internal_misc_Unsafe.java
Fixed the caught errors in Unsafe class
> FIX for Unsafe class

- src/classes/modules/java.base/java/lang/String.java
- src/peers/gov/nasa/jpf/vm/JPF_java_lang_String.java
Fixed the error related to `getBytes()` in String class.
> fix for String (getBytes())

- src/classes/modules/java.base/jdk/internal/misc/CDS.java
Created empty stub for CDS.java methods. Only for required ones.
> Create stub for CDS.java

- src/classes/modules/java.base/java/lang/String.java
Created method `repeat()` in `String.java`
> Create repeat() in String.java

- src/classes/modules/java.base/java/lang/System.java
1. Add `Logger` interface
2. add `getLogger()` method
> add Logger interface and getLogger() method

- src/classes/modules/java.base/jdk/internal/access/SharedSecrets.java
- src/classes/modules/java.base/jdk/internal/misc/Unsafe.java
- src/peers/gov/nasa/jpf/vm/JPF_java_lang_invoke_MethodHandles.java
- src/tests/gov/nasa/jpf/test/java/concurrent/FindVarHandleTest.java
We have added 3 Tests to test instance field and 3 for static field.....
> Tests and MethodHandle for Instance and Static Field

- src/classes/modules/java.base/java/lang/String.java
- src/classes/modules/java.base/java/lang/System.java
- src/classes/modules/java.base/jdk/internal/misc/Unsafe.java
- src/peers/gov/nasa/jpf/vm/JPF_java_util_Random.java
- src/peers/gov/nasa/jpf/vm/JPF_jdk_internal_misc_Unsafe.java
This PR includes temporary fix for "SecurityManager" and complete fix for "Unsafe#getObject(....)"
> Compiler Warning FIX 

- src/main/gov/nasa/jpf/jvm/JVMClassInfo.java
- src/tests/java17/RecordFeatureTest.java
Refactor `setBootstrapMethod()`
> Refactor boot strap method branch

- src/main/gov/nasa/jpf/jvm/ClassFile.java
- src/main/gov/nasa/jpf/jvm/ClassFilePrinter.java
- src/main/gov/nasa/jpf/jvm/ClassFileReader.java
- src/main/gov/nasa/jpf/jvm/ClassFileReaderAdapter.java
- src/main/gov/nasa/jpf/jvm/JVMClassInfo.java
- src/main/gov/nasa/jpf/vm/ClassInfo.java
- src/main/gov/nasa/jpf/vm/RecordComponentInfo.java
- Implemented `parseRecordAttribute()`.  
- Added support for printing record components in `ClassFilePrinter`.
> Record support

- src/classes/modules/java.base/java/util/regex/Matcher.java
- src/tests/java11/MatcherTest.java
Completed the TODO methods in the Java Matcher class, implementing toMatchResult().
> Completed TODO- MatchResult()
