javapathfinder/jpf-core

- .gitignore
This adds new entries to ignore IDE specific and auto generated files.
Fixes: #3
> Improve .gitignore file

- .travis.yml
Modify .travis.yml so that it builds against the latest available
oracle-jdk 10 that is provided from the PPA linuxuprising/java.
Upgrade Ant as module compilation is only available since Ant 1.9.7
Fixes: #17
> Modify .travis.yml to build against java-10 (#17)

- src/main/gov/nasa/jpf/vm/HashedAllocationContext.java
Use StackWalking API instead of the non-standard sun.misc.SharedSecrets API to access caller information.
This fixes errors:
[javac]   error: cannot find symbol
[javac]   symbol:   class SharedSecrets
[javac]   location: package sun.misc
[javac]   error: cannot find symbol
[javac]   symbol:   class JavaLangAccess
[javac]   location: class HashedAllocationContext
Fixes: #22
> Use StackWalker instread of sun.misc.SharedSecrets

- src/main/gov/nasa/jpf/vm/MJIEnv.java
Fixes the compile error:
error: package com.sun.org.apache.bcel.internal.generic does not exist
Fixes: #19
> Remove unused import com.sun.org.apache.bcel.internal.generic.InstructionConstants

- src/classes/modules/java.base/java/lang/Class.java
- src/classes/modules/java.base/java/lang/System.java
- src/classes/modules/java.base/jdk/internal/misc/JavaLangAccess.java
This fixes:
```
[javac] classes/modules/java.base/java/lang/System.java: error: cannot find symbol
[javac] import sun.reflect.ConstantPool;
```
```
[javac] classes/modules/java.base/java/lang/Class.java:274: error: cannot find symbol
[javac] native ConstantPool getConstantPool();
```
Fixes: #29
> Refactor references to sun.reflect.ConstantPool

- src/classes/modules/java.base/java/lang/System.java
- src/classes/modules/java.base/sun/reflect/annotation/AnnotationType.java
This fixes:
```
[javac] src/classes/modules/java.base/sun/reflect/annotation/AnnotationType.java:28: error: cannot find symbol
[javac] import sun.misc.SharedSecrets;
[javac]                ^
[javac]   symbol:   class SharedSecrets
[javac]   location: package sun.misc
```
```
[javac] src/classes/modules/java.base/java/lang/System.java:27: error: cannot find symbol
[javac] import sun.misc.SharedSecrets;
[javac]                ^
[javac]   symbol:   class SharedSecrets
[javac]   location: package sun.misc
```
```
[javac] src/classes/modules/java.base/sun/reflect/annotation/AnnotationType.java:52: error: cannot find symbol
[javac]     AnnotationType at = SharedSecrets.getJavaLangAccess().getAnnotationType(annotationClass);
[javac]                         ^
[javac]   symbol:   variable …
```
> Refactor references to sun.misc.SharedSecrets

- src/classes/modules/java.base/java/lang/System.java
This fixes:
```
[javac] src/classes/modules/java.base/java/lang/System.java:26: error: cannot find symbol
[javac] import sun.misc.JavaLangAccess;
[javac]                ^
[javac]   symbol:   class JavaLangAccess
[javac]   location: package sun.misc
```
and subsequent errors:
```
[javac] src/classes/modules/java.base/java/lang/System.java:68: error: cannot find symbol
[javac]   static JavaLangAccess createJavaLangAccess () {
[javac]          ^
[javac]   symbol:   class JavaLangAccess
[javac]   location: class System
```
```
[javac] src/classes/modules/java.base/java/lang/System.java:69: error: cannot find symbol
[javac]     return new JavaLangAccess(){
[javac]                ^
[javac]   symbol:   class JavaLangAccess
[javac]   location: class System
```
Fixes: #33
> Refactor references to sun.misc.JavaLangAccess

- src/classes/modules/java.base/java/lang/ClassLoader.java
Import sun.misc.CompoundEnumeration is unused in modules/java.base/java/lang/ClassLoader.java
And also ClassLoader and CompoundEnumeration both belongs to the same package, java.lang.
And we don't have any model class that overrides it.
Thus it is not required that we explicitly import it.
Fixes: #35
> Remove unused import sun.misc.CompoundEnumeration

- src/classes/modules/java.base/java/lang/String.java
Due to the implementation changes made to the standard Java String and
related classes in JEP 254 (Java 9 and later), JPF String model class
now fails to compile. This updates String model class to comply with the
internal API changes.
This make String model class to follow a internal representation similar
to the standard String class in Java 9 and later which uses byte array
plus an encoding-flag field instead of UTF-16 char array to represent a
String.
Fixes: #37
> Update String model class to comply with JEP 254

- src/classes/modules/java.base/jdk/internal/misc/SharedSecrets.java
This removes JavaOISAccess static field and accessor methods from
classes/modules/java.base/jdk/internal/misc/SharedSecrets.java
This fixes errors:
```
src/classes/modules/java.base/jdk/internal/misc/SharedSecrets.java:60: error: cannot find symbol
[javac]   private static JavaOISAccess javaOISAccess;
[javac]                  ^
src/classes/modules/java.base/jdk/internal/misc/SharedSecrets.java:162: error: cannot find symbol
[javac]   public static void setJavaOISAccess(JavaOISAccess access) {
[javac]                                       ^
src/classes/modules/java.base/jdk/internal/misc/SharedSecrets.java:166: error: cannot find symbol
[javac]   public static JavaOISAccess getJavaOISAccess() {
[javac]                 ^
```
Fixes: #38
> Remove JavaOISAccess from model class SharedSecrets

- src/classes/modules/java.base/jdk/internal/misc/JavaNetAccess.java
sun.misc.URLClassPath has been moved to the internal package:
java.base/jdk.internal.loader.URLClassPath
This fixes:
classes/modules/java.base/jdk/internal/misc/JavaNetAccess.java: error: cannot find symbol
[javac]   URLClassPath getURLClassPath (URLClassLoader ucl);
[javac]   symbol:   class URLClassPath
[javac]   location: interface JavaNetAccess
Fixes: #41
> Refactor references to URLClassPath

- src/main/gov/nasa/jpf/vm/ClassInfo.java
- src/tests/gov/nasa/jpf/test/vm/basic/MethodTest.java
The logic to detect if there are two conflicting default methods was incorrect.
If a class and its superclass both implement the same interface JPF should not
throw an IncompatibleClassChangeError.
> Fix incorrect IncompatibleClassChangeError in ClassInfo.getDefaultMethod

- build.xml
This modifies the JUnit output of ant target 'test'
- Send tests output to Ant's logging system 
- Stop the build process if a test fails
> Format output of ant 'test' target

- src/tests/gov/nasa/jpf/test/vm/reflection/ConstructorTest.java
- src/tests/gov/nasa/jpf/util/SparseClusterArrayTest.java
This is a follow-up to the PR: #58 
Fixes: #47
> Fixup for the PR: #58

- build.gradle
Gradle compile task was not considering the "build.properties" files.
This change updates the compile task to add the missing file and fixes Issue #64
> Copying build.properties to output dir 

- src/tests/gov/nasa/jpf/test/mc/basic/StackDepthCheckerTest.java
Seeting the stack frame depth (n) in here is also not very important. So removed.
Fixes: #62
> Remove countStackFrames() in StackDepthCheckerTest#testInfiniteRecursion

- src/main/gov/nasa/jpf/listener/PathOutputMonitor.java
- src/main/gov/nasa/jpf/tool/PrintEvents.java
- src/main/gov/nasa/jpf/util/ObjectConverter.java
- src/main/gov/nasa/jpf/util/test/TestJPF.java
- src/main/gov/nasa/jpf/vm/ClassInfo.java
- src/tests/gov/nasa/jpf/test/java/lang/ClassTest.java
- src/tests/gov/nasa/jpf/test/vm/basic/RecursiveClinitTest.java
Replaces all the occurrences of
clazz.newInstance()
in jpf-core with
clazz.getDeclaredConstructor().newInstance()
From
http://cr.openjdk.java.net/~iris/se/10/latestSpec/api/java/lang/Class.html#newInstance()
Class.newInstance() method propagates any exception thrown by the
nullary constructor, including a checked exception. Use of this method
effectively bypasses the compile-time exception checking that would
otherwise be performed by the compiler. The Constructor.newInstance
method avoids this problem by wrapping any exception thrown by the
constructor in a (checked) InvocationTargetException.
Fixes: #61
> Replaces all the occurrences of clazz.newInstance()

- build.xml
- src/peers/gov/nasa/jpf/vm/JPF_java_util_Random.java
This refactors sun.misc.Unsafe to jdk.internal.misc.Unsafe in
JPF_java_util_Random.java
So to fix the compiler warning:
[javac] /home/travis/build/javapathfinder/jpf-core/src/peers/gov/nasa/jpf/vm/JPF_java_util_Random.java:99:
warning: Unsafe is internal proprietary API and may be removed in a future release
However package jdk.internal.misc is declared in module java.base, which does
not export it to the unnamed module (src/peers)
So following compiler argument is neceesary to be added into javac ant
target of src/peers
<compilerarg value="--add-exports"/>
<compilerarg value="java.base/jdk.internal.misc=ALL-UNNAMED"/>
to prevent the error:
[javac] /home/gayan/git/javapathfinder/jpf-core/src/peers/gov/nasa/jpf/vm/JPF_java_util_Random.java:32:
error: package jdk.internal.misc is not …
> Refactor a reference to sun.misc.Unsafe

- src/tests/gov/nasa/jpf/test/java/text/DecimalFormatTest.java
Double (double) is deprecated. It is suggested that we use the static factory #valueOf(double), as it is likely to yield significantly better space and time performance.
This is a fixup for issue: #47
This is a follow-up to the PR: #59
>  Use valueOf instead of Double(double)

- src/main/gov/nasa/jpf/vm/ChoiceGeneratorBase.java
- src/main/gov/nasa/jpf/vm/choice/PermutationCG.java
Both constructors PermutationCG#PermutationCG(PermutationGenerator), ChoiceGeneratorBase#ChoiceGeneratorBase() is marked for removal. PermutationCG is annotated with @SuppressWarnings("removal") to suppress the warning:
[javac] src/main/gov/nasa/jpf/vm/choice/PermutationCG.java:35:
warning: [deprecation] ChoiceGeneratorBase() in ChoiceGeneratorBase has been deprecated
[javac]   public PermutationCG (PermutationGenerator pg){
[javac]                                                 ^
Fixes: #72
> Suppress warning ChoiceGeneratorBase() has been deprecated

- build.gradle
Sample of the generated build.properties file:
```
#JPF core build info
#Tue Jun 05 19:04:47 BRT 2018
java.version=1.8.0_151
user.country=US
date=2018-06-05 19\:00\:21 -0300
revision=4f636d3
author=Jeanderson Candido <jeandersonbc@gmail.com>
os.name=Mac OS X
os.arch=x86_64
```
> Created buildinfo task (#78)

- src/tests/gov/nasa/jpf/test/java/net/URLClassLoaderTest.java
ClassLoader.getPackage(String) is deprecated. This refactors URLClassLoaderTest to use ClassLoader.getDefinedPackage(String) instead.
gov.nasa.jpf.test.java.net.URLClassLoaderTest.TestClassLoader is only used within gov.nasa.jpf.test.java.net.URLClassLoaderTest.
gov.nasa.jpf.test.java.net.URLClassLoaderTest.TestClassLoader#getPackage
is being removed as it is no longer being used once the test being refactored.
Fixes: #71
> Refactor URLClassLoaderTest.testGetPackage to testGetDefinedPackage

- src/tests/TypeNameTest.java
- src/tests/gov/nasa/jpf/test/mc/data/CGCreatorFactoryTest.java
- src/tests/gov/nasa/jpf/test/mc/data/JSONTest.java
- src/tests/gov/nasa/jpf/util/SortedArrayObjectSetTest.java
If two objects are equal according to the equals(Object), then calling
the hashCode method on each of the two objects must produce the same
integer result.
However we have classes in src/tests that overrides equals(Object)
without overriding the hashCode method. This overrides the missing
hashCode methods.
Fixes: #85
> Override hashCode where equals is overridden

- src/tests/gov/nasa/jpf/test/mc/threads/FinalizerThreadTest.java
java.lang.Object#finalize is deprecated since Java 9.
`gov.nasa.jpf.test.mc.threads.FinalizerThreadTest.Finalize#finalize` is
not removed to stay compatible with (rare) programs using finalizers.
Fixes: #88
> Annotate FinalizerThreadTest.Finalize#finalize with @SuppressW…("deprecation")

- src/classes/modules/java.base/java/lang/ClassLoader.java
java.lang.ClassLoader#getResources in the model class java.lang.ClassLoader references java.lang.CompoundEnumeration which is an auxilary class declared within the java standard class
java/lang/ClassLoader.java
This adds a new auxilary class named EnumerationAdapter within the model class, as replacement for CompoundEnumeration class, so to prevent our ClassLoader model class from referencing an auxilary class from outside its own source file.
This fixes:
> warning: auxiliary class CompoundEnumeration in ClassLoader.java should not be accessed from outside its own source file
Fixes: #90
> Add new auxliary class EnumerationAdapter to ClassLoader

- build.xml
- src/main/gov/nasa/jpf/jvm/DirClassFileContainer.java
- src/main/gov/nasa/jpf/jvm/JVMClassFileContainer.java
- src/main/gov/nasa/jpf/jvm/JarClassFileContainer.java
- src/main/gov/nasa/jpf/vm/ClassFileContainer.java
This updates JVMClassFileContainer#getClassURL to comply with the URI structure used in the new Java Module System.
This is related to the issue #50 which is about JPF failing to load model classes from jpf-classes.jar due to different URI structure of the .class files being introuduced in Java Module System. The previous workaround introudced by the PR #51 is specifically for the jpf-classes.jar. JPF will still fail to locate classes from the other jar files.
Thus this reverts it. And make a implementation changes to JVMClassFileContainer#getClassURL which is JPF's universal container for holding Java class files.
> Update JVMClassFileContainer#getClassURL to comply with Module System

- src/main/gov/nasa/jpf/jvm/JVMClassInfo.java
- src/main/gov/nasa/jpf/vm/BootstrapMethodInfo.java
- src/tests/gov/nasa/jpf/test/java/lang/StringTest.java
JVMClassInfo.Initializer#setBootstrapMethod method assumes to have a bootstrap method with a structure similar to the following (which have 3 bootstrap method arguments)
```
BootstrapMethods:
0: #83 REF_invokeStatic java/lang/invoke/LambdaMetafactory.metafactory:(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite;
Method arguments:
#84 (Ljava/lang/Object;)Ljava/lang/Object;
#85 REF_invokeInterface java/lang/annotation/Annotation.annotationType:()Ljava/lang/Class;
#86 (Ljava/lang/annotation/Annotation;)Ljava/lang/Class;
```
In case JPF encounters a bootstrap method with arbitrary number of arguments such as the …
> Add a new constructor BootstrapMethodInfo(enclosingClass, cpArgs)

- src/main/gov/nasa/jpf/jvm/JRTClassFileContainer.java
- src/main/gov/nasa/jpf/jvm/JVMClassFileContainer.java
- src/main/gov/nasa/jpf/vm/ClassLoaderInfo.java
If a match is not found when resolving classes from the classpath, try to load that class from the run-time image.
References:
http://openjdk.java.net/jeps/220
Fixes: #94
> Add gov.nasa.jpf.jvm.JRTClassFileContainer

- src/peers/gov/nasa/jpf/vm/JPF_jdk_internal_reflect_Reflection.java
This fixes the run-time error "java.lang.UnsatisfiedLinkError: cannot find native jdk.internal.reflect.Reflection.getCallerClass"
```
[junit] java.lang.UnsatisfiedLinkError: cannot find native jdk.internal.reflect.Reflection.getCallerClass
[junit]     at jdk.internal.reflect.Reflection.getCallerClass(no peer)
```
Fixes: #103
> Rename JPF_sun_reflect_Reflection to JPF_jdk_internal_reflect_Reflection

- build.xml
- src/classes/modules/java.base/jdk/internal/misc/Unsafe.java
- src/peers/gov/nasa/jpf/vm/JPF_java_lang_Class.java
- src/peers/gov/nasa/jpf/vm/JPF_jdk_internal_misc_Unsafe.java
- src/tests/gov/nasa/jpf/test/java/misc/UnsafeTest.java
This implements the missing methods in Unsafe model class to prevent NoSuchMethodError(s), and their respective NativePeer methods in JPF_jdk_internal_misc_Unsafe to prevent UnsatisfiedLinkError(s).
```
[junit] java.lang.NoSuchMethodError: jdk.internal.misc.Unsafe.objectFieldOffset(Ljava/lang/Class;Ljava/lang/String;)J
```
```
[junit] java.lang.UnsatisfiedLinkError: cannot find native jdk.internal.misc.Unsafe.objectFieldOffset
```
Fixes: #99
> Implement missing, and/or unlinked native methods in Unsafe 

- build.xml
This opens java.base/jdk.internal.misc to the UNNAMED module (in junit ant target --test), so to prevent:
[junit] java.lang.IllegalAccessError: class gov.nasa.jpf.vm.JPF_java_util_Random (in unnamed module)
cannot access class jdk.internal.misc.Unsafe (in module java.base)
because module java.base does not export jdk.internal.misc to unnamed module
AND:
[junit] gov.nasa.jpf.JPFException: cannot access java.util.Random
internals: java.lang.reflect.InaccessibleObjectException: Unable to make
field private static final jdk.internal.misc.Unsafe
jdk.internal.misc.Unsafe.theUnsafe accessible: module java.base does not
"opens jdk.internal.misc" to unnamed module
Fixes: #107
> Open jdk.internal.misc to UNNAMED module in tests

- src/peers/gov/nasa/jpf/vm/JPF_jdk_internal_misc_VM.java
This fixes the JUnit error:
[junit] java.lang.UnsatisfiedLinkError: cannot find native jdk.internal.misc.VM.initialize
Fixes: #115
> Rename JPF_sun_misc_VM to JPF_jdk_internal_misc_VM

- src/peers/gov/nasa/jpf/vm/JPF_java_lang_StringUTF16.java
This adds a NativePeer class for java.lang.StringUTF16.
Also adds a native peer method for StringUTF16#isBigEndian() to fix:
[junit] java.lang.UnsatisfiedLinkError:
cannot find native java.lang.StringUTF16.isBigEndian
Fixes: #114
> Add native peer JPF_java_lang_StringUTF16

- src/classes/modules/java.base/jdk/internal/misc/SharedSecrets.java
Adds SharedSecrets#getJavaObjectInputFilterAccess and SharedSecrets#setJavaObjectInputFilterAccess methods to jdk.internal.misc.SharedSecrets model class.
This fixes:
```
[junit] java.lang.NoSuchMethodException:
jdk.internal.misc.SharedSecrets.setJavaObjectInputFilterAccess(Ljdk/internal/misc/JavaObjectInputFilterAccess;)V
```
Fixes: #111
> Add accessor methods for SharedSecrets#javaObjectInputFilterAccess

- src/classes/modules/java.base/jdk/internal/misc/SharedSecrets.java
Adds SharedSecrets#setJavaNetURLAccess and SharedSecrets#getJavaNetURLAccess methods to jdk.internal.misc.SharedSecrets model clsas.
This fixes:
[junit] java.lang.NoSuchMethodException:
jdk.internal.misc.SharedSecrets.setJavaNetURLAccess(Ljdk/internal/misc/JavaNetURLAccess;)V
Fixes: #109
> Add accessor methods for SharedSecrets#javaNetURLAccess

- src/classes/modules/java.base/java/lang/String.java
This refactors String model class based on JDK 10.0.1 source.
* Add support for JEP 254: Compact Strings, which fixes #118 
[junit] java.lang.NoSuchFieldError: java.lang.String.COMPACT_STRINGS
* Refactor String#contentEquals(java.lang.CharSequence) as the current implementation only handles UTF16
> Refactor String model class

- src/peers/gov/nasa/jpf/vm/JPF_java_lang_StackStreamFactory.java
Add a native peer method for StackStreamFactory#checkStackWalkModes to fix #113 :
```
[junit] java.lang.UnsatisfiedLinkError:
cannot find native java.lang.StackStreamFactory.checkStackWalkModes
```
> Add NativePeer JPF_java_lang_StackStreamFactory

- src/peers/gov/nasa/jpf/vm/JPF_jdk_internal_reflect_Reflection.java
Add NativePeer method `jdk.internal.reflect.Reflection#getClassAccessFlags(java.lang.Class)`
This fixes #106:
```
[junit] java.lang.UnsatisfiedLinkError:
cannot find native jdk.internal.reflect.Reflection.getClassAccessFlags
```
> Add NativePeer method for Reflection#getClassAccessFlags(Class)

- src/classes/modules/java.base/java/lang/Class.java
Add method java.lang.Class#getModule to  MJI model class for java.lang.Class
This also fixes #124 :
```
[junit] java.lang.NoSuchMethodError:
java.lang.Class.getModule()Ljava/lang/Module;
```
> Add java.lang.Class#getModule to MJI model class

- src/classes/modules/java.base/java/lang/String.java
The value returned by java.lang.String#length in the MJI model class for java.lang.String is incorrect, as the value field of String is now a byte array instead of a char array.
This updates String#length method to comply with JEP 254.
Fixes: #128
> Update String#length to comply with JEP 254

- src/classes/modules/java.base/jdk/internal/misc/SharedSecrets.java
Add `SharedSecrets#setJavaLangInvokeAccess` and `SharedSecrets#getJavaLangInvokeAccess` methods to MJI model class for jdk.internal.misc.SharedSecrets.
This fixes #130 :
```
[junit] java.lang.NoSuchMethodException:
jdk.internal.misc.SharedSecrets.getJavaLangInvokeAccess()Ljdk/internal/misc/JavaLangInvokeAccess;
```
> Add accessor methods for SharedSecrets#javaLangInvokeAccess

- src/classes/modules/java.base/java/lang/String.java
Add package private constructor `java.lang.String#String(byte[], byte)` to MJI model class for java.lang.String
This also fixes #135:
```
[junit] java.lang.NoSuchMethodException: Calling java.lang.String.<init>([BB)V
[junit]     at java.lang.StringLatin1.newString(StringLatin1.java:549)
```
> Add method java.lang.String#String(byte[], byte)

- src/classes/modules/java.base/java/lang/String.java
Add method java.lang.String.getBytes(byte[], int, byte) to MJI model class for java.lang.String
This also fixes #134:
```
[junit] java.lang.NoSuchMethodError: java.lang.String.getBytes([BIB)V
[junit] at java.lang.AbstractStringBuilder.putStringAt(AbstractStringBuilder.java:1641)
```
> Add method java.lang.String.getBytes(byte[], int, byte)

- src/peers/gov/nasa/jpf/vm/JPF_java_lang_String.java
When constructing the JVM string object 's2' in
gov.nasa.jpf.vm.JPF_java_lang_String#equals__Ljava_lang_Object_2__Z,
`argRef` should be used instead of `objRef`.
https://github.com/javapathfinder/jpf-core/blob/a95fd23e014d39fb01754125820cbe678dd559ab/src/peers/gov/nasa/jpf/vm/JPF_java_lang_String.java#L166-L173
Fixes: #140
> Fix invalid implementation of NativePeer method for String#equals

- src/peers/gov/nasa/jpf/vm/JPF_java_lang_String.java
When constructing the JVM string object `otherStr` , `strRef` should be used instead of `objRef`.
https://github.com/javapathfinder/jpf-core/blob/a95fd23e014d39fb01754125820cbe678dd559ab/src/peers/gov/nasa/jpf/vm/JPF_java_lang_String.java#L317-L324
Fixes: #141
> Fix invalid implementation of NativePeer method for String#concat

- src/classes/modules/java.base/java/lang/String.java
https://github.com/javapathfinder/jpf-core/blob/9ebb98cb53b952ea3d7c7dc06aa7b822ee696395/src/classes/modules/java.base/java/lang/String.java#L249-L260
Our initial conclusion that the coder is always UTF16 is wrong. As it states "If two coders are **different** and the target is big enough, invoker guarantees that the target is in UTF16 ". So the invoker guarantees not to call when the source encoding is UTF-8 and the target is in LATIN-1.
But what if the source and target encoding are in "UTF-8". So the assertion statement needs to be removed.
This also fixes:
[junit] java.lang.AssertionError
[junit]     at java.lang.String.getBytes(String.java:254)
The error can be seen on ObjectStreamTest, ClassLoaderTest, StringTest and in a few other tests.
> Remove unnecessary assertion in String#getBytes(byte[], int, byte)

- src/main/gov/nasa/jpf/vm/MJIEnv.java
- src/peers/gov/nasa/jpf/vm/JPF_java_lang_reflect_Array.java
- src/tests/gov/nasa/jpf/test/java/lang/reflect/FieldTest.java
Fixes and unit tests for #151. As mentioned in the issue, env.get/setShortField was incorrectly forwarding to get/setIntField.
> Fix get/setShort for field and array reflection

- src/main/gov/nasa/jpf/vm/FunctionObjectFactory.java
- src/tests/java8/LambdaTest.java
Fixes and unit test for #147. As mentioned in the issue, there was no null check when unpacking object values.
> Fixes null captured parameters

- src/main/gov/nasa/jpf/vm/ClassInfo.java
- src/tests/java8/DefaultMethodTest.java
Fixes #154. Now when multiple potential default method resolutions, we check whether one type is a subinterface of the other and select the more specific type. If the two types are not in a subtyping relation, we fail as before.
In addition, the looping algorithm was changed because the old version did not consider super interfaces. This commit includes a unit test to test this behavior.
> Fixes default method resolution

- src/classes/java/lang/Throwable.java
- src/tests/gov/nasa/jpf/test/java/lang/ThrowableTest.java
Fixes #148. We just need to set cause in the no-arg throwable constructor to this.
> Fixes setCause on default exception

- src/classes/gov/nasa/jpf/AnnotationProxyBase.java
- src/classes/java/lang/reflect/Method.java
- src/main/gov/nasa/jpf/jvm/ClassFile.java
- src/main/gov/nasa/jpf/jvm/ClassFilePrinter.java
- src/main/gov/nasa/jpf/jvm/ClassFileReader.java
- src/main/gov/nasa/jpf/jvm/ClassFileReaderAdapter.java
- src/main/gov/nasa/jpf/jvm/JVMAnnotationParser.java
- src/main/gov/nasa/jpf/jvm/JVMClassInfo.java
- src/main/gov/nasa/jpf/jvm/SkipAnnotation.java
- src/main/gov/nasa/jpf/vm/MJIEnv.java
- src/peers/gov/nasa/jpf/vm/JPF_gov_nasa_jpf_AnnotationProxyBase.java
- src/peers/gov/nasa/jpf/vm/JPF_java_lang_Class.java
- src/peers/gov/nasa/jpf/vm/JPF_java_lang_String.java
- src/peers/gov/nasa/jpf/vm/JPF_java_lang_reflect_Method.java
- src/tests/gov/nasa/jpf/test/vm/basic/AnnotationDefaultValueReflectionTest.java
- src/tests/gov/nasa/jpf/test/vm/basic/AnnotationHashCodeEqualsTest.java
- src/tests/gov/nasa/jpf/test/vm/basic/AnnotationToStringTest.java
- src/tests/gov/nasa/jpf/test/vm/basic/MissingAnnotationClassTest.java
Closes #150. Improves toString to cover all primitive types and annotation
attributes. Also adds support for:
* Default value reflection
* hashCode/equals on annotations
* nested annotations
* Ignoring missing annotations (which is what the JVM does)
> Improves annotation support

- bin/jpf-sv-comp
Benchexec is the benchmarking framework used
by SV-COMP.
https://github.com/sosy-lab/benchexec (PR#309 + PR#313)
It can be run using the benchmark definition in
https://github.com/sosy-lab/sv-comp (PR#83)
and the benchmarks in
https://github.com/sosy-lab/sv-benchmarks (PR#565)
This first version of the script does the job for now.
Comments how to generalize it in future are highly appreciated.
> Run script for Benchexec

- src/main/gov/nasa/jpf/vm/StackFrame.java
- src/tests/gov/nasa/jpf/vm/StackFrameTest.java
The condition "attrs is not null" is written as (attrs==null), instead of (attrs != null).
My patch is as follow:
. -    if (attrs == null){
. +   if (attrs != null){
.          attrs[index] = ObjectList.replace(attrs[index], oldAttr, newAttr);    
.       }
> [fix-bug]: checking attrs is not null in method StackFrame:replaceLocalAttr( )

- gradle/wrapper/gradle-wrapper.properties
- src/classes/java/util/regex/Matcher.java
- src/peers/gov/nasa/jpf/vm/JPF_java_util_regex_Matcher.java
- src/tests/gov/nasa/jpf/test/java/io/PrintStreamTest.java
The model and peer classes java.util.regex.Matcher are modified to accommodate the overloading of the function find() , the lack of which was causing the error.
> Rectifies the java.lang.NoSuchMethodError when usinf printf

- src/examples/ConcurrentCount.java
- src/examples/ConcurrentCount.jpf
The jpf example CocnurrentCount can be used to compare the performance of different jpf-core implementations/search techniques. The state-space's size can be greatly varied by changing the variable "COUNT" which further helps in making comparisons.
> Implements a jpf example ConcurrentCount

- src/main/gov/nasa/jpf/search/SearchListener.java
- src/main/gov/nasa/jpf/search/SearchListenerAdapter.java
Fixed up some of the spelling mistakes in the documentation for SearchListener.java. Added verbosity to the documentation for the class and method descriptions as well as extra details regarding each method and its usage.
> Expanded the javadoc for SearchListener.java and SearchListenerAdapter.java

- src/main/gov/nasa/jpf/vm/NativePeer.java
- src/peers/gov/nasa/jpf/vm/JPF_java_util_concurrent_atomic_AtomicReference.java
- src/tests/gov/nasa/jpf/test/java/concurrent/AtomicReferenceTest.java
Hi needed this to get a minimal Scala-Futures example running. Maybe this is useful for others too. The code is basically the same as for AtomicInteger.
> Add Peer for java.util.concurrent.atomic.AtomicReference

- .travis.yml
There's a known issue in travis xenial environment. It only supports JDK versions 9-11.
> Fix issue #187: use ubuntu trusty version for travis build environment

- src/peers/gov/nasa/jpf/vm/JPF_java_lang_String.java
- src/tests/gov/nasa/jpf/test/java/lang/StringTest.java
Fixed an off-by-one error in the model class implementation of the method `String.lastIndexOf()` in `JPF_java_lang_String`. Initially the for-loop counter always excludes 0 as the last index, whereas it should have been included in the search.
> Fixed off-by-one error in String.lastIndexOf() method (#197)

- src/peers/gov/nasa/jpf/vm/JPF_java_lang_StringBuilder.java
- src/tests/gov/nasa/jpf/test/java/lang/StringTest.java
Fixed a zero-capacity error in the model class implementation of the method `StringBuilder.append(char c)` in `JPF_java_lang_StringBuilder`. Initially when capacity is set to 0 for the constructor during a StringBuilder object instantiation, the JPF's implementation for the `append(char c)` will throw an `illegal array offset: 0` exception when the method is called. The behavior for the standard StringBuilder library is to allow such appends even when the capacity has been first set to 0. Thus, for the JPF's implementation, we first need to allocate a default array if the initial capacity is 0.
> Fixed zero-capacity error in StringBuilder.append(char c) method (#201)

- src/main/gov/nasa/jpf/search/RandomSearch.java
- src/tests/gov/nasa/jpf/test/mc/basic/StatelessTest.java
Right now the `RandomSearch` always returns after finishing one path, this PR tries to fix this problem and allow it to explore mutiple paths specified by `search.RandomSearch.path_limit`. The previous code will fail the added test but should pass after merged. 
Now after `cg.randomize_choices` set to not `NONE` , the search will randomly try different paths.
> fixed random search where only one path is explored even with limit > 1

- src/classes/sun/misc/SharedSecrets.java
The failing test `testSimpleReadbackOk` throws `NoSuchMethodException`. It can be reproduced by running the following command.
`gradle test --tests gov.nasa.jpf.test.java.io.ObjectStreamTest.testSimpleReadbackOk --info`
My Java version is `openjdk 1.8.0_252`.
The stack trace is as follows
`gov.nasa.jpf.vm.NoUncaughtExceptionsProperty
java.lang.NoSuchMethodException: sun.misc.SharedSecrets.setJavaObjectInputStreamReadString(Lsun/misc/JavaObjectInputStreamReadString;)V
at java.io.ObjectInputStream.<clinit>(ObjectInputStream.java:3986)
at gov.nasa.jpf.test.java.io.ObjectStreamTest.testSimpleReadbackOk(ObjectStreamTest.java:88)
at java.lang.reflect.Method.invoke(gov.nasa.jpf.vm.JPF_java_lang_reflect_Method)
at gov.nasa.jpf.util.test.TestJPF.runTestMethod(TestJPF.java:648)
`
The fix is to add …
> Fix testSimpleReadbackOk Test

- src/classes/java/util/regex/Pattern.java
The failing test `testBufferConstructor` throws `NoSuchMethodException`, which can be reproduced using the following command:
`gradle test --tests gov.nasa.jpf.test.java.nio.ByteBufferTest.testBufferConstructor --info`
I use Java version openjdk 1.8.0_252. The stacktrace is as follows:
`gov.nasa.jpf.vm.NoUncaughtExceptionsProperty
java.lang.NoSuchMethodException: java.util.regex.Pattern.quote(Ljava/lang/String;)Ljava/lang/String;`
`at java.util.Scanner.useLocale(Scanner.java:1196)`
`at java.util.Scanner.<init>(Scanner.java:540)`
`at java.util.Scanner.<init>(Scanner.java:702)`
`at gov.nasa.jpf.test.java.nio.ByteBufferTest.testBufferConstructor(ByteBufferTest.java:40)`
`at java.lang.reflect.Method.invoke(gov.nasa.jpf.vm.JPF_java_lang_reflect_Method)`
`at …
> Fix testBufferConstructor Test

- src/classes/modules/java.base/java/lang/ClassLoader.java
- src/classes/modules/java.base/java/lang/System.java
- src/classes/modules/java.base/java/lang/Thread.java
- src/classes/modules/java.base/java/lang/invoke/JPFFieldVarHandle.java
- src/classes/modules/java.base/java/security/SecureClassLoader.java
- src/classes/modules/java.base/jdk/internal/misc/JavaLangAccess.java
- src/classes/modules/java.base/jdk/internal/misc/Unsafe.java
- src/main/gov/nasa/jpf/jvm/JVMClassFileContainer.java
- src/main/gov/nasa/jpf/jvm/JarClassFileContainer.java
- src/main/gov/nasa/jpf/jvm/bytecode/VirtualInvocation.java
- src/main/gov/nasa/jpf/vm/ThreadInfo.java
- src/main/gov/nasa/jpf/vm/VM.java
- src/peers/gov/nasa/jpf/vm/JPF_java_lang_ClassLoader.java
- src/peers/gov/nasa/jpf/vm/JPF_java_lang_invoke_JPFFieldVarHandle.java
- src/peers/gov/nasa/jpf/vm/JPF_java_lang_invoke_MethodHandles$Lookup.java
I could fix 4 of the tests in a reasonable way bringing it down to 11 remaining test cases to complete #274:
```
ObjectStreamTest. testSimpleReadbackOk
RuntimeTest. testAvailableProcessors
StackWalkerTest. testCallerClass
DateFormatTest. testConversionCycle
DateFormatTest. testFormatWithTimeZone
DateFormatTest. testSetAndGetTimeZone
SimpleDateFormatTest. testFormatWithTimeZone
RecursiveClinitTest. testNewInstance
ProxyTest. testAnnoProxy
ProxyTest. testBasicProxy
InterruptTest. testPark
SAXParserTest. testSimpleParse 
```
> Fix some of the failing tests in #274

- build.gradle
- src/main/gov/nasa/jpf/vm/serialize/PolDetSerializer.java
- src/peers/JPF_PolDetListener.java
- src/tests/PolDet/PolDetExamples.java
- src/tests/PolDet/PolDetMain.java
PolDet (Pollution Detection) implementation using Java PathFinder. This tool detects JUnit tests that pollute the shared program state. For more information, read our paper accepted by JPF workshop 2021: https://y553546436.github.io/files/jpf_sen.pdf .
PolDet implementation is in the following three files:
1. src/tests/PolDet/PolDetMain.java
2. src/peers/JPF_PolDetListener.java
3. src/main/gov/nasa/jpf/vm/serialize/PolDetSerializer.java
File PolDetMain.java contains class PolDetMain, the entry class to run PolDet. It also contains PolDetListener class, a specialized JUnit listener to call our code before and after the test. File JPF_PolDetListener.java contains the peer class for PolDetListener class. File PolDetSerializer.java contains a specialized JPF state serializer which ignores …
> add PolDet (Pollution Detection) implementation

- .github/workflows/simple_build.yml
- build.gradle
I just have read #290. Actually, I have a version of the gradle file that allows to use jpf-core as build by jitpick.io.
See our jdart buildfile for more details: https://github.com/tudo-aqua/jdart/blob/2c3e24be0a7726e5f3821928f157a4ad72b0e5d2/build.gradle.kts#L40
> Add ptml plugin

- src/main/gov/nasa/jpf/vm/Verify.java
The failing test case in #294 seems related to this assert statement. If I remove it, the test passes. But I have no clue how this effects in a side effect the ExchangerTest. If we remove it, everything work on my system.
Any ideas why this is the case?
> Remove assert in verify class

- src/classes/java/lang/ThreadLocal.java
- src/tests/ThreadLocalTest/App.java
Added method 
public static <S> ThreadLocal<S> withInitial(Supplier<? extends S> supplier) {
return new SuppliedThreadLocal<>(supplier);
}
> The static method java.lang.ThreadLocal.withInitial is added  On line 99

- src/tests/java11/StringConcatenationTest.java
Add string concatenation tests involving toString(), which currrently fail in Java 11, as the object itself is passed into StringConcatFactory.makeConcatWithConstants() during the invokedynamic call. This issue was described in #258.
> Add failing string concat tests (Java 11)

- src/classes/java/lang/System.java
- src/main/gov/nasa/jpf/vm/ClassInfo.java
This fixes #325, as the testSimpleReadbackOk runs correctly in Java 8 after this patch.
Note that this is not the complete implementation in initializeSystemClass(), but the minimum of what is required to fix this test case.
> Save properties in VM

- build.gradle
Updating the git-version plugin to `"com.dmdirc.git-version"` 
- This plugin is supported for git-submodule
> Updating the git-version plugin

- src/tests/java8/functionTest/FunctionsTest.java
- src/tests/java8/timeTest/ClockTest.java
- src/tests/java8/timeTest/LocalDateTest.java
Import statements are declared in wrong manner in [jpf-core](https://github.com/javapathfinder/jpf-core)/[src](https://github.com/javapathfinder/jpf-core/tree/master/src)/[tests](https://github.com/javapathfinder/jpf-core/tree/master/src/tests)/[java8](https://github.com/javapathfinder/jpf-core/tree/master/src/tests/java8)/java.timeTest/   and   [jpf-core](https://github.com/javapathfinder/jpf-core)/[src](https://github.com/javapathfinder/jpf-core/tree/master/src)/[tests](https://github.com/javapathfinder/jpf-core/tree/master/src/tests)/[java8](https://github.com/javapathfinder/jpf-core/tree/master/src/tests/java8)/java.util.functionTest/
> Updating Import statments

- src/main/gov/nasa/jpf/jvm/bytecode/JVMArrayElementInstruction.java
- src/tests/gov/nasa/jpf/test/mc/threads/RaceTest.java
This should fix #344 
I submit to the branch `java-10-gradle` as I work on Java 11.
Four unit tests are added according to @cyrille-artho's suggestions. I have run `gradlew build` and found no regression errors. (Some tests failed due to JPF's unimplemented features on Java 11)
> Fix PreciseRaceDetector false alarms (#344)

- src/main/gov/nasa/jpf/jvm/bytecode/VirtualInvocation.java
- src/tests/gov/nasa/jpf/test/vm/basic/MethodTest.java
This should fix #348 
This bug only exists on Java 11 so only in `java-10-gradle` branch. A unit test is also provided.
I have run `./gradlew clean check` locally and find no regressions. (There are still 13 test failures as JPF doesn't fully support Java 11 yet.)
> Fix a bug in private method dispatch (#348)

- src/classes/modules/java.base/java/lang/String.java
- src/main/gov/nasa/jpf/jvm/bytecode/INVOKEDYNAMIC.java
- src/main/gov/nasa/jpf/vm/FunctionObjectFactory.java
- src/tests/java11/StringConcatenationTest.java
This PR should fix the following two failing string concat tests, which are parts of #274.
```
java11.StringConcatenationTest::testStringConcatenationWith_toString
java11.StringConcatenationTest::testStringConcatenationWith_toStringNested
```
I have tested locally and find that it fixes these two failing tests with no more regressions (11 failing tests left now).
From JDK 9, the default implementation of string concat is changed to use `invokedynamic`. In OpenJDK's implementation, during the execution of `invokedynamic`, it generates bytecode dynamically to convert the args of string concat to the right data type (for example, call `toString()` of the reference type) and concatenate them.
In the current implementation of JPF, during using `invokedynamic` to do string concat, it doesn't …
> Fix string concat bug of not calling correct toString() method

- src/peers/gov/nasa/jpf/vm/JPF_java_lang_Class.java
- src/tests/gov/nasa/jpf/test/java/lang/ClassTest.java
- src/tests/gov/nasa/jpf/test/vm/basic/RecursiveClinitTest.java
This is a backport of #353 on `master` branch. This patch is a little bit different from that one because of some file differences.
> Fix a not-throwing-exception bug in Class.newInstance, a backport of PR #353

- src/tests/gov/nasa/jpf/test/java/lang/RuntimeTest.java
This PR should fix the following failing test, which is a part of #274.
```
gov.nasa.jpf.test.java.lang.RuntimeTest::testAvailableProcessors
```
I have tested locally and found that it fixes this test case with no more regressions (10 failing tests left now).
This may not be a bug of JPF, but a bug of the unit test.
In the execution of this test case, **`Runtime.availableProcessors()` is called twice, thus generating `2*2=4` states instead of the asserted 2**. Except for an explicit invocation in the test case, JPF's initialization also invokes it once. The following content explains how this happens.
In the initialization phase of JPF, it loads and initializes some system classes, including `java.lang.System`. **For JPF running on OpenJDK 11**, the static initializer `<clinit>` of …
> Fix the bug in the test case for Runtime.availableProcessors()

- src/peers/gov/nasa/jpf/vm/JPF_java_lang_Class.java
- src/tests/gov/nasa/jpf/test/java/lang/ClassTest.java
This PR should fix a bug that, in some cases, execution should throw an exception, but it doesn't on JPF. And a test case for this bug is added. This patch may also apply to `master` branch (on OpenJDK 8).
I have tested locally on `java-10-gradle` branch; this fix brings no regressions (still, 11 failing tests left). 
According to Java API doc for [java.lang.Class.newInstance()](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Class.html#newInstance()), the following code snippet should throw `InstantiationException`. (It falls into the category of "the class has no nullary constructor"). But it doesn't throw any exception on JPF.
```
public class Main {
static class C {
int i;
public C(int i) {
this.i = i;
}
}
public static void main (String[] args) throws Exception …
```
> Fix a not-throwing-exception bug in Class.newInstance

- src/tests/gov/nasa/jpf/test/vm/basic/RecursiveClinitTest.java
This PR should fix the following failing test, which is a part of #274.
```
gov.nasa.jpf.test.vm.basic.RecursiveClinitTest::testNewInstance
```
I have tested locally and found that it fixes this test case with no more regressions (10 failing tests left now).
This is not a bug of JPF but instead a bug of the test case.
Running on JPF, this test case thows the following exception:
```
gov.nasa.jpf.vm.NoUncaughtExceptionsProperty
java.lang.AssertionError: instantiation failed with java.lang.NoSuchMethodException: gov.nasa.jpf.test.vm.basic.RecursiveClinitTest$Derived.<init>()
at gov.nasa.jpf.util.test.TestJPF.fail(TestJPF.java:164)
at gov.nasa.jpf.test.vm.basic.RecursiveClinitTest.testNewInstance(RecursiveClinitTest.java:72)
at java.lang.reflect.Method.invoke(gov.nasa.jpf.vm.JPF_java_lang_ref …
```
> Fix a bug in test case of RecursiveClinitTest

- src/classes/modules/java.base/java/lang/reflect/Proxy.java
- src/peers/gov/nasa/jpf/vm/JPF_java_lang_reflect_Proxy.java
- src/tests/gov/nasa/jpf/test/vm/reflection/ProxyTest.java
This patch adds Proxy support for JPF on Java 11 and some unit tests. It should fix the following two failing unit tests, which are parts of #274.
```
gov.nasa.jpf.test.vm.reflection.ProxyTest::testAnnoProxy
gov.nasa.jpf.test.vm.reflection.ProxyTest::testBasicProxy
```
I have tested locally and found that it fixes these two test cases with no more regressions (7 failing tests left now).
In OpenJDK 11, `Proxy.newInstance()` involves too much code that JPF currently does not fully support; we need to add a model class for `java.lang.reflect.Proxy` and use JPF's way to implement a simpler one but with the same functionality.
According to [doc of `getProxyClass()`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/reflect/Proxy.html#getProxyClass(java.lang.ClassLoader,java …
> Add Proxy support for JPF on Java 11

- src/main/gov/nasa/jpf/jvm/JVMClassInfo.java
- src/tests/java8/LambdaTest.java
This patch should fix the bug in implementing bytecode behavior for method handle of kind `REF_newInvokeSpecial`. It is also a preliminary work for supporting `StackWalker` APIs. It adds a unit test and should bring no regressions (still 7 test failures left).
According to [specification](https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-5.html#jvms-5.4.3.5), current implementation loses a `dup` bytecode thus returning the wrong value.
> Fix the bytecode behavior implementation of REF_newInvokeSpecial method handle

- src/main/gov/nasa/jpf/jvm/ClassFile.java
- src/tests/java8/LambdaTest.java
This patch should fix a subtle bug that causes loading of a class with many BSMs to fail. This is also a preliminary work for supporting `StackWalker` APIs. It adds a unit test and should bring no regressions (still 7 test failures left).
`invokeDynamicIndex` is used to map bootstrap method to `invokedynamic` in CP
https://github.com/javapathfinder/jpf-core/blob/b94d1aed34391b6722ff4f4d686a9f471cec6070/src/main/gov/nasa/jpf/jvm/ClassFile.java#L95-L97
Its size should have been equal to the number of BSMs. But it is initialized to a constant value.
https://github.com/javapathfinder/jpf-core/blob/b94d1aed34391b6722ff4f4d686a9f471cec6070/src/main/gov/nasa/jpf/jvm/ClassFile.java#L106-L108
This hard-coding size bug will surely cause OOB exception during JPF’s loading a class containing many …
> Fix the bug of incorrect mapping from bootstrap method index to invokedynamic CP index

- src/classes/modules/java.base/java/lang/StackFrameInfo.java
- src/peers/gov/nasa/jpf/vm/JPF_java_lang_StackStreamFactory.java
- src/tests/gov/nasa/jpf/test/java/lang/StackWalkerTest.java
This patch adds `java.lang.StackWalker` API support for JPF on Java 11. It mainly implements two native method calls, `callStackWalk` and `fetchStackFrames`. Please refer to code comments for detailed implementation ideas.
It should fix the following failing test mentioned in #274 and bring no more regressions.
```
gov.nasa.jpf.test.java.lang.StackWalkerTest::testCallerClass
```
After this patch, there are still 6 unit test failures left in JPF on Java 11.
Support for `StackFrameInfo.toStackTraceElement()` and `StackFrameInfo.getMethodType()` is left for further improvement. Since I think they might not be frequently used, but are sort of complicated, and need another PR.
> Implement StackWalker API for JPF on Java 11

- src/tests/gov/nasa/jpf/test/java/lang/StackWalkerTest.java
This should fix #361. It adds a lock to eliminate unnecessary state transitions to speed up the unit test `testStackWalkerInCaseOfChoiceGenerator`.
> Update unit test `testStackWalkerInCaseOfChoiceGenerator` to speed it up

- src/classes/modules/java.base/java/lang/Class.java
- src/classes/modules/java.base/jdk/internal/misc/SharedSecrets.java
- src/main/gov/nasa/jpf/jvm/JVMClassFileContainer.java
- src/peers/gov/nasa/jpf/vm/JPF_java_lang_System.java
- src/peers/gov/nasa/jpf/vm/JPF_jdk_internal_misc_VM.java
- src/peers/gov/nasa/jpf/vm/JPF_jdk_internal_reflect_ReflectionFactory.java
- src/tests/gov/nasa/jpf/test/java/io/ObjectStreamTest.java
This patch should fix the issue that appears when `ObjectInputStream` reads an object thus adding object stream API support for JPF on Java 11.
It should fix the following failing test mentioned in #274 and bring no more regressions.
```
gov.nasa.jpf.test.java.io.ObjectStreamTest::testSimpleReadbackOk
```
After this patch, there might be still 5 unit test failures left in JPF on Java 11.
> Add object stream support for JPF on Java 11

- src/main/gov/nasa/jpf/jvm/JVMClassInfo.java
- src/tests/java8/LambdaTest.java
A constructor takes the new object as its _first_ argument. This patch modifies bytecode generation for `REF_NEW_INVOKESPECIAL` to load the new object _before_ any other arguments to a constructor.
Submitting pull request to the `java-10-gradle` branch, where the previous fix (#359) is located.
> Bytecode for REF_newInvokeSpecial: load new object as first argument

- src/peers/gov/nasa/jpf/vm/JPF_java_lang_Class.java
- src/tests/gov/nasa/jpf/test/java/lang/ClassTest.java
For example, in the current implementation `Class.forName("[B")` fails with:
> java.lang.ClassNotFoundException: class not found: B
which should be fixed by this patch. The type resolution is based on that of `INSTANCEOF.execute` ([here](https://github.com/javapathfinder/jpf-core/blob/1f99a23a095e89b22b71539dc238ba5d73231a6d/src/main/gov/nasa/jpf/jvm/bytecode/INSTANCEOF.java#L40) and [here](https://github.com/javapathfinder/jpf-core/blob/1f99a23a095e89b22b71539dc238ba5d73231a6d/src/main/gov/nasa/jpf/jvm/bytecode/INSTANCEOF.java#L45-L60)).
(Incidentally, `Class.forName("[B")` does work in unit tests because [there exists](https://github.com/javapathfinder/jpf-core/blob/1f99a23a095e89b22b71539dc238ba5d73231a6d/src/tests/TypeNameTest.java#L31) a class named `B` in the unnamed package.)
> Fixed Class.forName for primitive array types

- src/main/gov/nasa/jpf/vm/Allocation.java
- src/tests/gov/nasa/jpf/vm/AllocationTest.java
Without this check, two `Allocation` objects with the same context, same hash, but different counts will be erroneously treated as equal.
> gov.nasa.jpf.vm.Allocation.equals: added missing equality check for the count field

- src/main/gov/nasa/jpf/jvm/JVMClassInfo.java
- src/main/gov/nasa/jpf/vm/ClassInfo.java
- src/main/gov/nasa/jpf/vm/FunctionObjectFactory.java
- src/tests/java8/LambdaTest.java
This patch should fix #378 and some other bugs in lambda expression's capturing local primitive types of different storage sizes (on branch `java-10-gradle`). A unit test is also added.
I have run `./gradlew clean check` locally and find no regressions.
> Fix bugs in some calculations related to field sizes of function object created for `invokedynamic` (#378)

- src/main/gov/nasa/jpf/vm/FunctionObjectFactory.java
- src/tests/java8/LambdaTest.java
This patch should fix #379. A local run of `./gradlew clean check` shows no regression.
> Fix a bug of lambda expression’s capturing wrong reference type local variable (#379)

- src/peers/gov/nasa/jpf/vm/JPF_java_lang_Class.java
- src/tests/gov/nasa/jpf/test/java/lang/reflect/FieldTest.java
- src/tests/gov/nasa/jpf/test/mc/basic/FinalBreakTest.java
- src/tests/gov/nasa/jpf/test/vm/reflection/FieldTest.java
- src/tests/gov/nasa/jpf/test/vm/reflection/FieldVisibilityTest.java
* Class.getField should return only public fields
* Added comments on the behavior of `Class.getField` and `Class.getDeclaredField`
(Same as #384)
> Class.getField should return only public fields

- src/peers/gov/nasa/jpf/vm/JPF_java_lang_reflect_Field.java
- src/tests/gov/nasa/jpf/test/java/lang/reflect/FieldTest.java
- src/tests/gov/nasa/jpf/test/java/lang/reflect/other_package/OtherPackageParent.java
- src/tests/gov/nasa/jpf/test/java/lang/reflect/other_package/OtherPackagePublicClass.java
This PR:
* Fixes issue: `final` fields cannot be read via reflection because `isAccessible` returns `false` on final fields regardless of whether the access is a read or a write: https://github.com/javapathfinder/jpf-core/blob/f0e39060944bff59ef5a970ad155bd82dcbb265f/src/peers/gov/nasa/jpf/vm/JPF_java_lang_reflect_Field.java#L102-L104
* Contains a more complete implementation of reflection field-access checking.
I _believe_ this implementation is complete with respect to OpenJDK 8, except for two behaviors:
1. OpenJDK 8 seems to disallow writing to a static final field using reflection, even if overridden with `setAccessible(true)` (https://github.com/openjdk/jdk8u/blob/0bec498fc945a49f1134e02eb477e0af15db3b5b/jdk/src/share/classes/sun/reflect/UnsafeFieldAccessorFactory.java#L38). This …
> More complete implementation of Field.isAccessible

- src/main/gov/nasa/jpf/jvm/bytecode/INSTANCEOF.java
- src/main/gov/nasa/jpf/vm/ElementInfo.java
- src/main/gov/nasa/jpf/vm/Types.java
- src/tests/gov/nasa/jpf/test/java/lang/ClassLoaderTest.java
- src/tests/gov/nasa/jpf/test/java/lang/ClassTest.java
This method's declaration currently reads `instanceOf(String, String)`, taking both the LHS and RHS types as type signature strings.  As a result, to use a `ClassInfo` object `ci` as the LHS, a caller must convert it into a string via `ci.getType()` (see `ElementInfo.instanceOf`), before the string eventually gets turned back into a `ClassInfo` object (if it's a reference type) in the method body.
This patch changes the method declaration to read `instanceOf(ClassInfo, String)`.  This change not only saves the back-and-forth, but also addresses the case where the LHS class has been loaded by a non-default class loader, in which case the original implementation fails to resolve its type string back into a `ClassInfo`.  Fixes https://github.com/javapathfinder/jpf-core/issues/383.
This patch …
> Modify Types.instanceOf to take a ClassInfo as LHS

- src/classes/modules/java.base/java/util/regex/Matcher.java
- src/main/gov/nasa/jpf/vm/MJIEnv.java
- src/peers/gov/nasa/jpf/vm/JPF_java_lang_reflect_Field.java
- src/peers/gov/nasa/jpf/vm/JPF_java_util_regex_Matcher.java
- src/tests/gov/nasa/jpf/test/java/io/PrintStreamTest.java
This commit contains 2 patches:
1. Use java.lang.Character instead of java.lang.char and adds the PrintStreamTest - commit [f7336c4](https://github.com/javapathfinder/jpf-core/commit/f7336c4df1322b1d586c0ebc34c10fd57f340667#diff-23f2449034ab5d4b6acf3bade57e37bac214f7bc9b40e1949b38bc3f48c700a8)
2. Fixes the PrintStreamTest's printf() method - #172 
None of the 934 tests break
> Apply patch to add PrintStreamTest and add patch for #172 to fix PrintStreamTest

- src/tests/gov/nasa/jpf/test/java/util/CalendarTest.java
Imports patch to add the CalendarTest originally defined as part of #181 
1 new test added. Does not break anything. All of the 935 tests pass.
> Apply patch for #181 to add CalendarTest

- src/main/gov/nasa/jpf/vm/NativePeer.java
- src/peers/gov/nasa/jpf/vm/JPF_java_util_concurrent_atomic_AtomicReference.java
- src/tests/gov/nasa/jpf/test/java/concurrent/AtomicReferenceTest.java
This patch adds a new test `AtomicReferenceTest`
All tests (934) pass.
> Apply patch for #182 to add peer and test for AtomicReference

- src/main/gov/nasa/jpf/jvm/bytecode/DDIV.java
- src/tests/gov/nasa/jpf/test/java/lang/DoubleTest.java
- src/tests/gov/nasa/jpf/test/java/lang/FloatTest.java
The original patch can be found [here](https://github.com/javapathfinder/jpf-core/commit/5cfe5f6b3052fc76ef16c15ad11a177c479c1920).
Two tests have been added:
1. `DoubleTest.java`
2. `FloatTest.java`
All the 935 tests pass. Patch does not break anything.
Thanks!
> Apply patch to fix division by zero in DDIV and adds 2 tests

- src/peers/gov/nasa/jpf/vm/JPF_java_lang_Runtime.java
- src/tests/gov/nasa/jpf/test/java/lang/RuntimeTest.java
Original commit can be found [here](https://github.com/javapathfinder/jpf-core/commit/c42e4fc591a787c17954e63dbbc2cf9668c6ae39).
Adds 2 tests:
1. `RuntimeTest.testExit()`
2. `RuntimeTest.testHalt()`
All tests pass (945).
Thanks!
> Apply patch to add support for halt() in the Runtime peer

- src/tests/gov/nasa/jpf/test/java/io/FileIOTest.java
Original commit can be found [here](https://github.com/javapathfinder/jpf-core/commit/2fc7c6100c2bb7cf4452ecfd72a628d6c06e3188).
The patch adds one new test to the `FileIOTest` test:
1. `testRedirection()`
All of the 944 tests pass.
Thanks!
> Apply patch to add test for redirection of stdout to a file

- src/main/gov/nasa/jpf/report/Publisher.java
- src/tests/gov/nasa/jpf/test/basic/ConsolePublisherTest.java
The original commit can be found [here](https://github.com/javapathfinder/jpf-core/commit/d275f72b1878404b0b4d80a4845969d3370f0e06).
The patch also defines a new test class `ConsolePublisherTest.java` which defines 5 tests.
All 948 tests pass.
Thanks!
> Apply patch to add missing else-if block to Publisher's publishStart()

- .github/workflows/simple_build.yml
- build.gradle
- src/main/gov/nasa/jpf/vm/serialize/PolDetSerializer.java
- src/peers/JPF_PolDetListener.java
- src/tests/PolDet/PolDetExamples.java
- src/tests/PolDet/PolDetMain.java
Adds pollution detection as part of #285 :
- To review: Classes `PolDetExamples` and `PolDetMain` within `tests/PolDet` use the **GPL v3** license. 
Adds the gradle task testPolDet to the CI build via `simple_build.yml`
Thanks!
> Apply patch for #285 and #289 to implement pollution detection and to add the gradle task

- src/annotations/gov/nasa/jpf/annotation/BitFlip.java
- src/main/fault/injection/examples/APISimpleExample.java
- src/main/fault/injection/examples/AnnotationSimpleExample.java
- src/main/fault/injection/examples/BCDEncodedISBN.java
- src/main/fault/injection/examples/CRC.java
- src/main/fault/injection/examples/CheckISBN.java
- src/main/fault/injection/examples/LongEncodedCRC.java
- src/main/gov/nasa/jpf/listener/BitFlipListener.java
- src/main/gov/nasa/jpf/vm/JPF_gov_nasa_jpf_vm_Verify.java
- src/main/gov/nasa/jpf/vm/StackFrame.java
- src/main/gov/nasa/jpf/vm/Types.java
- src/main/gov/nasa/jpf/vm/Verify.java
- src/tests/fault/injection/examples/BCDEncodedISBNTest.java
- src/tests/fault/injection/examples/CRCTest.java
- src/tests/fault/injection/examples/CheckISBNTest.java
- src/tests/fault/injection/examples/LongEncodedCRCTest.java
- src/tests/gov/nasa/jpf/test/mc/data/BitFlipTest.java
#297 refactors `Verify.java` to resolve a bug introduced by #295
#299 refactors `Verify.java` to have native qualifiers instead of empty method bodies for multiple methods
Five test classes have been added in as a result of the patch which add a total of 27 tests:
1. `BCDEncodedISBNTest.java`
2. `CRCTest.java`
3. `CheckISBNTest.java`
4. `LongEncodedCRCTest.java`
5. `BitFlipTest.java`
Thanks!
> Apply patches for #295 to add extension to systematically inject and test for bit-flip faults 

- src/classes/modules/java.base/java/lang/ThreadLocal.java
- src/tests/gov/nasa/jpf/test/java/lang/ThreadLocalTest.java
The patch contained problems and works after refactors/changes.
Changes made:
1. `withInitial()` was incorrectly defined inside the `SuppliedThreadLocal` class
2. `ThreadLocalTest.java` was not defined correctly. Both the test and the package structure has been corrected.
Thanks!
> Apply patch for #301 to add withInitial and add a unit test

- src/tests/gov/nasa/jpf/test/java/util/java.timeTest/ClockTest.java
- src/tests/gov/nasa/jpf/test/java/util/java.timeTest/LocalDateTest.java
The patch contains commit to add the timeTest package containing the 2 tests mentioned and @cyrille-artho's [commit](https://github.com/javapathfinder/jpf-core/commit/2f8f3c4dc847b8945fc13d2cb60896fc9c34265b) to use a modern API for the troublesome `ClockTest`.
All the tests(961) pass.
Thanks!
> Apply patch for #312, to add timeTest: ClockTest and LocalDateTest

- build.gradle
'maven-publish' plugin is used to support publishing to the local maven repository.
No new tests added.
Thanks!
> Apply patch for #296, to add maven-publish plugin support

- src/classes/modules/java.base/java/nio/Buffer.java
- src/classes/modules/java.base/java/nio/ByteBuffer.java
- src/classes/modules/java.base/java/nio/CharBuffer.java
- src/classes/modules/java.base/java/text/NumberFormat.java
- src/classes/modules/java.base/java/util/regex/Matcher.java
- src/classes/modules/java.base/java/util/regex/Pattern.java
- src/peers/gov/nasa/jpf/vm/JPF_java_util_regex_Matcher.java
- src/tests/gov/nasa/jpf/test/java/nio/BufferTest.java
- src/tests/gov/nasa/jpf/test/java/nio/ByteBufferTest.java
- src/tests/gov/nasa/jpf/test/java/text/DecimalFormatTest.java
The patch #171 adds a new test `ByteBufferTest` which fails from a different stack trace than the time the issue was first observed. Therefore the incremental fix as part of #244 does not apply.
The `ByteBufferTest`'s `testBufferConstructor()` currently fails with the stack trace below:
`====================================================== error 1
gov.nasa.jpf.vm.NoUncaughtExceptionsProperty
java.lang.NoSuchFieldError: java.nio.HeapCharBuffer.UNSAFE
at java.nio.HeapCharBuffer.<clinit>(HeapCharBuffer.java:45)
at java.nio.CharBuffer.allocate(CharBuffer.java:348)
at java.util.Scanner.<init>(Scanner.java:538)
at java.util.Scanner.<init>(Scanner.java:766)
at gov.nasa.jpf.test.java.nio.ByteBufferTest.testBufferConstructor(ByteBufferTest.java:40)
at …
> Apply patch for #171, to add support for java.nio.Buffer

- src/main/gov/nasa/jpf/vm/serialize/PolDetSerializer.java
- src/peers/JPF_PolDetListener.java
- src/tests/PolDet/PolDetExamples.java
- src/tests/PolDet/PolDetMain.java
Four files originally added to `master` as part of #285, which adds support for pollution detection, were making use of the GPL License v3.0. The patch to the `java-10-gradle` branch was added as part of #402 
The project `jpf-core` is licensed under Apache License v2.0, which leads to a conflict in license usage. Therefore, the four affected files have been updated to follow the Apache License.
Thanks!
> Fix license conflicts by updating code to use the Apache License v2.0

- build.gradle
- jpf.properties
- src/main/gov/nasa/jpf/jvm/bytecode/INSTANCEOF.java
- src/main/gov/nasa/jpf/vm/ClassInfo.java
- src/main/gov/nasa/jpf/vm/ElementInfo.java
- src/main/gov/nasa/jpf/vm/Types.java
- src/peers/gov/nasa/jpf/vm/JPF_java_lang_ClassLoader.java
- src/tests/gov/nasa/jpf/test/java/lang/ClassLoaderTest.java
- src/tests/gov/nasa/jpf/test/java/lang/ClassTest.java
Hello @cyrille-artho and @pparizek,
This PR combines a set of related patches which add functionality and fix bugs. The patches involved here are #203, #208, #209 and #388, which means #410 can now be skipped as it is same as #388 minus the unit test in `ClassLoaderTest`.
The patch adds a total of 6 unit tests. All 1002 tests now pass.
Some refactors were necessary in the `build.gradle` file to comply the added dependency for **asm** and the task with the latest gradle version.
Thanks!
> Adds recursive lookup for ClassLoader.defineClass() and unit tests

- build.gradle
Currently the code coverage stands at 49% for instructions and 42% for branches.
This implies that almost half the instructions remain untested and a thorough review would be necessary to ascertain addition of new tests to cover these missing instructions and branches.
Thanks!
> Add JaCoCo gradle plugin to support code coverage monitoring for #417

- build.gradle
Retain jacocoTestReport as a standalone task which can be run by executing the command `./gradlew jacocoTestReport`
> Disable the jacoco task from executing by default. 

- src/classes/modules/java.base/java/lang/reflect/Method.java
Created `toShortSignature()` in `Method.java`
> Create toShortSignature() in Method.java

- src/classes/modules/java.base/java/lang/Class.java
add descriptorString() method in Class.java
> add descriptorString() method in Class.java

- src/classes/modules/java.base/java/lang/Class.java
- src/classes/modules/java.base/java/lang/ClassLoader.java
- src/tests/gov/nasa/jpf/test/java/net/URLClassLoaderTest.java
- I have created a test case in `URLClassLoaderTest` which is failing because `Pcakage.toString()` method is not working and throwing `NullPointerException`
> `Package.toString()` not working in JPF

- src/main/gov/nasa/jpf/vm/ThreadInfo.java
- src/tests/gov/nasa/jpf/test/java/concurrent/ThreadExceptionTest.java
JPF is failing the added test `ThreadExceptionTest` because it does not terminate a thread when an unhandled exception occurs. This PR fixed this issue by continuing to execute the `DIRECTCALLRETURN` instruction instead of throwing the UncaughtException.
> Terminate the thread when unhandled exception happens.

- src/tests/gov/nasa/jpf/test/vm/threads/SuspendResumeTest.java
add SuppressWarnings(removal) against Thread.resume(),Thread.suspend() to avoid the Compiler Warning as there is no clear substitute.
> SuppressWarnings(removal) against Thread.resume(),Thread.suspend()

- src/peers/gov/nasa/jpf/vm/JPF_jdk_internal_misc_Unsafe.java
the native peers method present in the `\src\peers\gov\nasa\jpf\vm` had a  "mangled" which was old so it has been corrected to the new location which is `\jdk\internal\misc`
> change the mangeld of the method signature 

- src/main/gov/nasa/jpf/listener/VarTracker.java
- src/tests/gov/nasa/jpf/listener/VerTrackerTest.java
This PR fixes the error when we run an empty main set to a VerTracker listener. 
#380
I added a test that calls the empty main method setting the listener to VerTracker.
###Fix :
-  The error was reflected because the addOperandAttr() method was called in the VerTracker without checking if the 
operand stack was empty.
-  The if condition `(frame.getTopPos() >= 0)` checks for the above undetected condition.
> Fixed the error when Empty main runs with VerTracker

- src/classes/modules/java.base/java/nio/ByteBuffer.java
- src/classes/modules/java.base/java/nio/CharBuffer.java
- src/tests/CharBufferTest.java
The Test that was created showed several methods missing which was then implemented and the error was fixed successfully 
This PR addresses Fixes #343
> fixed NoSuchMethodError: java.nio.StringCharBuffer.nextGetIndex 

- src/main/gov/nasa/jpf/jvm/JVMClassInfo.java
- src/tests/java17/RecordFeatureTest.java
1. Add Tests for record feature
2. modification in setBootstrap(...)
> Record Feature Progress

- build.gradle
`compileTestJava` should reply on `compileModulesJava`. The vscode will throw an error when running a single test without this change
> add missing dep
